### ISSUE TITLE
Test execution fails with message KeyError

### ISSUE THREAD

**Issue by v1k45** [primal100/pybitcointools#1]
I tried running the tests but it threw the following exception:
```
(pybtc)  % python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from bitcoin import cryptos
  File "/home/vikas/code/oss/pybitcointools/bitcoin/cryptos/__init__.py", line 1, in <module>
    from .bitcoin import  Bitcoin
  File "/home/vikas/code/oss/pybitcointools/bitcoin/cryptos/bitcoin.py", line 3, in <module>
    from .constants import COIN_METADATA
  File "/home/vikas/code/oss/pybitcointools/bitcoin/cryptos/constants.py", line 3, in <module>
    COIN_METADATA = {coin['coin_symbol']: coin for coin in COIN_SYMBOL_ODICT_LIST}
  File "/home/vikas/code/oss/pybitcointools/bitcoin/cryptos/constants.py", line 3, in <dictcomp>
    COIN_METADATA = {coin['coin_symbol']: coin for coin in COIN_SYMBOL_ODICT_LIST}
KeyError: 'coin_symbol'
```

I checked the constants module of blockcypher, the dict seems to have `coin_symbol` key in it. But I don't understand why it gets removed while running.

**Comment by primal100** [comment]
I changed around the implementation. Bitcoin Testnet test cases are working now.
