### ISSUE TITLE
Can I use multi signature for bitcoin cash?

### ISSUE THREAD

**Issue by geethsameer686** [primal100/pybitcointools#11]
Is multisignature supports bitcoin cash? I can't sign the transaction for bitcoin cash. It is working for bitcoin and dash but not bitcoin cash. Could you explain?

**Comment by primal100** [comment]
Can you provide an example, and a full exception trace. Makes it easier to troubleshoot. Thanks.

**Comment by geethsameer686** [comment]
```
from cryptos import *
coin = BitcoinCash(testnet=True)
publickeys = ['04943ca5a3bf3e4ed456769a74ab0a69c032092685300a453c4b64a168deae09e9b16427a60e452295de4a9272112abbe2e7f8b578719c79839c58c89fe7397664',
			  '040c661c51a8ee3b01ccfe797714a04665a3adffe8b86943d57c58a68d929af97511a4b9afadab062e05cfbccc73a48ccba18a0c9992db510afd10a26849d5e782',
			  '0424f5b4094ce2a7d36661db60bc9b6418233792158a27b75dd414a1cbb1436ca48cb88491fe3f65fdc63fa1dec156d5cdb83a445b7d49077878d53770df1bc51f',
			  '044e37ee56e008e3a1b3272bd826a12997d582e1b799d62e58b82305ef4f28d17b3a61a35fa9e8441538c5afad2eb01d06fb68e96bd9b154f3638af6a99faa53aa',
			  '0449b610c91abe20cca6c19fa68a8af6a3681ad8e79ba649e2f425f048b2542939b5a1aa14550d7a5c7beeed80aca7e119979f3dfe58836038a8e08f32ace18653']
script, address = coin.mk_multsig_address(publickeys, 3)
tx = coin.preparetx("2N2CiwoXWYZoALhSQshPX5ryH9cw2hmfcJK", "mw71JWHmXPjBLn7RTKppp1bUYYpAwAja7m", 1100000, 50000, change_addr = "2N2CiwoXWYZoALhSQshPX5ryH9cw2hmfcJK")
for i in range(0, len(tx['ins'])):
	sig1 = coin.multisign(tx, i, script, "1cd7b58730e6514d24e051e2ec4c6a404f33d01ba18232c10404c2d21b96a8db")
	sig2 = coin.multisign(tx, i, script, "b0bc267daf08c971b1fc3872f3b12298308f22f32e2cb4fbc005a3da2f9b736c")
	sig3 = coin.multisign(tx, i, script, "48d5dbf0b373e92058e6b5367f8b7ae197fb166e757b8f22edbe5d9ba16e8b7e")
	tx = apply_multisignatures(tx, i, script, sig1, sig2, sig3)
print(coin.pushtx(tx))
```
The above code I used exactly to push the transaction. 
Error: 
```
Traceback (most recent call last):
  File "bitcoin_cash_testing_1.py", line 23, in <module>
    sig1 = coin.multisign(tx, i, script, "1cd7b58730e6514d24e051e2ec4c6a404f33d01ba18232c10404c2d21b96a8db")
  File "/root/anaconda3/lib/python3.6/site-packages/cryptos/coins/base.py", line 223, in multisign
    return multisign(tx, i, script, pk, self.hashcode)
  File "/root/anaconda3/lib/python3.6/site-packages/cryptos/transaction.py", line 433, in multisign
    modtx = signature_form(tx, i, script, hashcode)
  File "/root/anaconda3/lib/python3.6/site-packages/cryptos/transaction.py", line 222, in signature_form
    return uahf_digest(newtx, i)
  File "/root/anaconda3/lib/python3.6/site-packages/cryptos/transaction.py", line 197, in uahf_digest
    o.append(encode_8_bytes(inp['amount']))
KeyError: 'amount'
```

**Comment by geethsameer686** [comment]
Could you please explain why it is giving an error? Waiting for your answer

**Comment by primal100** [comment]
Bitcoin Cash needs the 'amount' key to create the signature but this is not provided in multisig at the moment.

**Comment by argcoin** [comment]
Hi, I am testing with python 2.7 and it returns this error 

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from cryptos import *
  File "/home/ger/.local/lib/python2.7/site-packages/cryptos/__init__.py", line 10, in <module>
    from .coins import *
  File "/home/ger/.local/lib/python2.7/site-packages/cryptos/coins/__init__.py", line 1, in <module>
    from .bitcoin import *
  File "/home/ger/.local/lib/python2.7/site-packages/cryptos/coins/bitcoin.py", line 1, in <module>
    from ..explorers import blockchain
  File "/home/ger/.local/lib/python2.7/site-packages/cryptos/explorers/__init__.py", line 1, in <module>
    from . import base_insight, bitpay, blockcypher, blockdozer, dash_siampm, sochain
  File "/home/ger/.local/lib/python2.7/site-packages/cryptos/explorers/blockcypher.py", line 5
    def unspent(*addrs, coin_symbol=None, api_key=None, **kwargs):
                                  ^
SyntaxError: invalid syntax
