### ISSUE TITLE
SyntaxError: invalid syntax on import

### ISSUE THREAD

**Issue by sampipe** [primal100/pybitcointools#19]
Hi ...

I'm trying to utilise your amazing library but not getting very far unfortunately... I'm on a mac and did a standard pip install.  When I import I am getting a syntax error below...  Is there anything obvious I'm going wrong?... i.e. does it need python 3*  etc... 

Appreciate any pointers.. 

Sam

MuleMacTop:processor sampipe$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptos import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/cryptos/__init__.py", line 10, in <module>
    from .coins import *
  File "/Library/Python/2.7/site-packages/cryptos/coins/__init__.py", line 1, in <module>
    from .bitcoin import *
  File "/Library/Python/2.7/site-packages/cryptos/coins/bitcoin.py", line 1, in <module>
    from ..explorers import blockchain
  File "/Library/Python/2.7/site-packages/cryptos/explorers/__init__.py", line 1, in <module>
    from . import base_insight, bitpay, blockcypher, blockdozer, dash_siampm, sochain
  File "/Library/Python/2.7/site-packages/cryptos/explorers/blockcypher.py", line 5
    def unspent(*addrs, coin_symbol=None, api_key=None, **kwargs):
                                  ^
SyntaxError: invalid syntax
>>>

**Comment by sampipe** [comment]
So I tried this on python 3* on a linux machine and it works as expected.  I suppose I will dev off this.

**Comment by gaborpapp** [comment]
I bumped into this as well on macos with Python 2.7.10.
This requires python 3+ I think (https://legacy.python.org/dev/peps/pep-3102/)
also reported in #13

**Comment by primal100** [comment]
Python 2 no longer supported.
