### ISSUE TITLE
Error calling inspect function

### ISSUE THREAD

**Issue by chentz78** [primal100/pybitcointools#65]
Hi,

I'm traying to use the inspect function to decode the 'outs'  from a raw BTC transaction. When I run my test code I get this error:
```
Traceback (most recent call last):
  File "/tmp/p3.py", line 13, in <module>
    print(c.inspect(txr))
  File "/opt/python3.9/lib/python3.9/site-packages/cryptos/coins/base.py", line 331, in inspect
    return self._run_async("inspect", tx)
  File "/opt/python3.9/lib/python3.9/site-packages/cryptos/coins/base.py", line 84, in _run_async
    return fut.result(timeout=self.timeout * 2)
  File "/opt/python3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/opt/python3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/python3.9/lib/python3.9/site-packages/cryptos/coins/base.py", line 68, in run
    result = await asyncio.wait_for(coro, timeout=self.timeout)
  File "/opt/python3.9/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/opt/python3.9/lib/python3.9/site-packages/cryptos/coins_async/base.py", line 1068, in inspect
    prevout = (await anext(self.get_txs(h)))['outs'][i]
NameError: name 'anext' is not defined
```

The code is :
```
import cryptos as C
from pprint import pprint

txr = "020000000001013b97b2b1cbc0ce16a6fb648f6ff2cc4b99a6ee8bef5d7810c33bf0db50b209e40100000000ffffffff02384a00000000000022512019bb1553602cd439a742bf2f17fb654eeffc427cd5b55504d7ebf6f221de6d82d4240b0000000000225120eb27ecb5decad5b77f1d7cc75a1ff4e08dbbe5aacb83c95446573caac9c427fb01401bcb5fd039634f815d5397db03b26cef7859a3f4953db28a0eaefc91552cf8dda51690922176d55bb376976c58f1451d7b2f7b2b620c549b104d90f55fcc0cc100000000"

print(CT.public_txhash(txr))

c = C.Bitcoin()
print(c.inspect(txr))
```

And my version is 2.0.9 and Python 3.9.16. The transaction ID is `6728b6b56d6e5f29ae7f05dc1f3320115240ac880bc09d63d4af86d0978fccf4`

**Comment by primal100** [comment]
Sorry but minimum Python3.10 is needed now. Will update the readme to reflect this.
